name: Unit test

on:
    pull_request:
    push:
      branches: [main]

jobs:
    test:
        name: Test on Node ${{matrix.node}}
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node: ['18.x']

        steps:
          - uses: actions/checkout@v3

          - name: Use Node.js ${{matrix.node}}
            uses: actions/setup-node@v3
            with:
              cache: npm
              node-version: ${{matrix.node}}
          
          - name: Install dependencies
            run: |
              node --version
              npm --version
              npm install

          - name: Run test
            run: npm run test:coverage
